import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Utility/Navbar";
import SignIn from "./auth/signIn";
import SetPassword from "./auth/setPassword";
import Regester from "./auth/regester";
import ContactsTable from "@/components/Home/contacts/ContactsTable";
import ExportViaEmail from "@/components/Home/contacts/ExportViaEmail";
import Footer from "@/components/Utility/Footer";
import UsersTable from "@/components/Home/users/UsersTable"; 
import CreateNewContact from "@/components/Home/contacts/CreateNewContact";
import InviteNewUser from "@/components/Home/users/InviteNewUser";
import EditContact from "@/components/Home/contacts/EditContact";
import EditUser from './../components/Home/users/EditUser';
import SendEmail from "@/components/Home/users/SendEmail";
import ChangePassword from "./auth/changePassword";
import Activities from "@/components/Home/contacts/Activities";
import Dashboard from "@/components/Home/dashboard"; 
import ContactsBook from "./../components/Home/contacts/ContactBook";
import CompanyProfile from "@/components/Home/company";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Contact Book App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      {/* <main > */}

        {/* <SignIn/> */}


        {/* <CompanyProfile/> */}
        {/* <SendEmail/> */}
        {/* <EditUser/> */}



        {/* <InviteNewUser/> */}



        {/* <EditContact/> */}
        {/* <CreateNewContact/> */}
        {/* <UsersTable/> */}
        {/* <ExportViaEmail/> */}
        {/* <ContactsTable/> */}

        {/* <Regester/>  */}
        {/* <SetPassword/> */}
        {/* <ChangePassword/> */}
        
        {/* <Dashboard/> */}
        {/* <Activities/> */}
        {/* <ContactsBook/> */}
        
      {/* </main> */}
    </>
  );
}
